name: fcai_student_login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  uuid:
  path_provider: ^2.0.15
  provider: ^6.0.5
  email_validator: ^2.1.17
  image_picker: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_selector_windows: ^0.9.3
  file_selector: ^1.0.1
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
